<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RainCore</RootNamespace>
    <AssemblyName>RainCore.Project</AssemblyName>
  </PropertyGroup>

                                                                      
                                                                         
                                                                         
                                                                               
                                                                          
                                                                                                                
                                                                          
                                                                          
                                                                           
                                                                      
                                                                         
                                 
  <ItemGroup>
    <ProjectReference Include="..\RainCore.Core\RainCore.Core.csproj" />
    <ProjectReference Include="..\RainCore.Scene\RainCore.Scene.csproj" />
  </ItemGroup>

</Project>
