<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
                                                                                  
                                                                          
                                                                              
                                                                           
                                                                             
                             
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RainCore.UI</RootNamespace>
    <AssemblyName>RainCore.UI</AssemblyName>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

                                                                              
                                                                        
                                                                              
                                                                              
                                                                              
                                                                           
                                                                             
                                          

                                                                         
                                                                              
                                                                              
                                                                             
                                                                       
                                                                        
                                          

                                                                             
                                                                              
  <ItemGroup>
    <ProjectReference Include="..\RainCore.Graphics\RainCore.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

</Project>
